import "./globals.css";
import "./loader.css";
import { Outfit } from "next/font/google";
import Provider from "@/lib/Providers/provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "AI note",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Provider>{children}</Provider>
       <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  )
}
