name: Build and deploy Next.js SSR app to Azure Web App - ai-notes-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload artifacts (optional backup)
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            public
            package.json
            package-lock.json
            node_modules

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A5D826ECCE449CDA906C563C19F7605 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DDA7B982B9F14EA7A4A6C9F20D8F7092 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6914C0E28DA343959A3F111DADBD6F43 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-notes-app'
          slot-name: 'Production'
          package: .
